import { Client, Project, Invoice, CashFlowLedgerEntry, DeveloperProfile } from '../types/erp';

export const INITIAL_DEVELOPER_PROFILE: DeveloperProfile = {
  developerName: 'Ibrahim Tarek',
  developerTitle: 'Software Engineer & Consultant',
  developerEmail: 'ibrahimtarek1965@outlook.com',
  developerPhone: '+20 1019804919',
  developerTaxId: 'EG-TX-89240182',
  developerAddress: 'Alexandria, Egypt',
  bankName: 'Commercial International Bank (CIB)',
  accountHolder: 'Ibrahim Tarek',
  iban: 'EG380010004500000192837461928',
  swift: 'CIBEGXXX',
  baseCurrency: 'EGP',
  exchangeRates: {
    USD: 49.25,
    EUR: 53.60,
    EGP: 1.0,
  },
};

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'c1-apex-systems',
    name: 'Sarah Jenkins',
    email: 'sarah@apexcloud.io',
    company: 'Apex Cloud Systems Inc.',
    defaultCurrency: 'USD',
    paymentTermsDays: 15,
    taxId: 'US-EIN-94-2819034',
    address: '500 Howard Street, Suite 400, San Francisco, CA 94105, USA',
    createdAt: '2026-01-10',
  },
  {
    id: 'c2-kinetix-gmbh',
    name: 'Markus Vogel',
    email: 'm.vogel@kinetix-tech.de',
    company: 'Kinetix Digital GmbH',
    defaultCurrency: 'EUR',
    paymentTermsDays: 30,
    taxId: 'DE-VAT-309182744',
    address: 'Friedrichstraße 120, 10117 Berlin, Germany',
    createdAt: '2026-02-01',
  },
  {
    id: 'c3-nilepay',
    name: 'Karim Mansour',
    email: 'karim@nilepay.app',
    company: 'NilePay Digital Solutions',
    defaultCurrency: 'EGP',
    paymentTermsDays: 15,
    taxId: 'EG-TX-71029411',
    address: 'Nile City Towers, 19th Floor, Corniche El Nil, Cairo, Egypt',
    createdAt: '2026-02-15',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'p1-distributed-cache',
    clientId: 'c1-apex-systems',
    title: 'Distributed Event-Driven Cache Layer',
    billingType: 'Fixed',
    totalBudget: 12500,
    status: 'Active',
    startDate: '2026-08-01',
    description: 'High-throughput Redis & Kafka messaging bridge with auto-scaling Kubernetes worker pods.',
    milestones: [
      {
        id: 'm1-1',
        title: 'Architecture Blueprint & Benchmark Harness',
        amount: 3500,
        dueDate: '2026-08-20',
        status: 'Billed',
      },
      {
        id: 'm1-2',
        title: 'Core Redis Pub/Sub Replication Engine',
        amount: 5000,
        dueDate: '2026-09-15',
        status: 'Completed',
      },
      {
        id: 'm1-3',
        title: 'Load Testing, Failover Clustering & Handover',
        amount: 4000,
        dueDate: '2026-10-15',
        status: 'Pending',
      },
    ],
  },
  {
    id: 'p2-kinetix-crm',
    clientId: 'c2-kinetix-gmbh',
    title: 'Enterprise Workflow Automation Engine',
    billingType: 'Hourly',
    totalBudget: 9600,
    hourlyRate: 120,
    estimatedHours: 80,
    status: 'Active',
    startDate: '2026-08-15',
    description: 'Custom React & Node microservices for processing real-time telemetry and ERP webhooks.',
    milestones: [
      {
        id: 'm2-1',
        title: 'Sprint 1: Schema Ingestion & Webhook Gateway (40 hrs)',
        amount: 4800,
        dueDate: '2026-09-05',
        status: 'Billed',
      },
      {
        id: 'm2-2',
        title: 'Sprint 2: Async Job Queue & Notification Engine (40 hrs)',
        amount: 4800,
        dueDate: '2026-10-05',
        status: 'Pending',
      },
    ],
  },
  {
    id: 'p3-nilepay-gateway',
    clientId: 'c3-nilepay',
    title: 'Instant Payment Network (IPN) Integration',
    billingType: 'Fixed',
    totalBudget: 180000,
    status: 'Active',
    startDate: '2026-09-01',
    description: 'Compliant central bank security gateway connector with HSM signing modules.',
    milestones: [
      {
        id: 'm3-1',
        title: 'Security Compliance Audit & HSM Interface',
        amount: 70000,
        dueDate: '2026-09-18',
        status: 'Billed',
      },
      {
        id: 'm3-2',
        title: 'Production Staging E2E Sandbox Tests',
        amount: 60000,
        dueDate: '2026-10-10',
        status: 'Pending',
      },
      {
        id: 'm3-3',
        title: 'Live Production Cutover & SRE Runbook',
        amount: 50000,
        dueDate: '2026-11-01',
        status: 'Pending',
      },
    ],
  },
  {
    id: 'p4-apex-advisory',
    clientId: 'c1-apex-systems',
    title: 'Quarterly Cloud Architecture Retainer',
    billingType: 'Retainer',
    totalBudget: 4500,
    status: 'Active',
    startDate: '2026-09-01',
    description: 'Monthly 25 hours on-demand architecture reviews, security auditing, and tier-3 incident escalation.',
    milestones: [
      {
        id: 'm4-1',
        title: 'September 2026 Retainer Allocation',
        amount: 4500,
        dueDate: '2026-09-01',
        status: 'Billed',
      },
      {
        id: 'm4-2',
        title: 'October 2026 Retainer Allocation',
        amount: 4500,
        dueDate: '2026-10-01',
        status: 'Pending',
      },
    ],
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-2026-001',
    invoiceNumber: 'INV-2026-001',
    projectId: 'p1-distributed-cache',
    clientId: 'c1-apex-systems',
    issueDate: '2026-08-20',
    dueDate: '2026-09-04',
    currency: 'USD',
    exchangeRateToLocal: 49.25,
    status: 'Paid',
    paidDate: '2026-09-02',
    items: [
      {
        id: 'item-1',
        description: 'Architecture Blueprint & Benchmark Harness (Milestone 1)',
        quantity: 1,
        unitPrice: 3500,
        amount: 3500,
      },
    ],
    subtotal: 3500,
    taxRate: 0,
    total: 3500,
    notes: 'Thank you for your business. Payment received via international wire.',
    paymentDetails: {
      bankName: 'Commercial International Bank (CIB)',
      accountHolder: 'Ibrahim Tarek',
      iban: 'EG380010004500000192837461928',
      swift: 'CIBEGXXX',
    },
  },
  {
    id: 'inv-2026-002',
    invoiceNumber: 'INV-2026-002',
    projectId: 'p2-kinetix-crm',
    clientId: 'c2-kinetix-gmbh',
    issueDate: '2026-09-05',
    dueDate: '2026-10-05',
    currency: 'EUR',
    exchangeRateToLocal: 53.60,
    status: 'Sent',
    items: [
      {
        id: 'item-2',
        description: 'Sprint 1: Schema Ingestion & Webhook Gateway (40 hrs @ €120/hr)',
        quantity: 40,
        unitPrice: 120,
        amount: 4800,
      },
    ],
    subtotal: 4800,
    taxRate: 0,
    total: 4800,
    notes: 'Reverse charge applicable. VAT exempt according to § 13b UStG.',
    paymentDetails: {
      bankName: 'Commercial International Bank (CIB)',
      accountHolder: 'Ibrahim Tarek',
      iban: 'EG380010004500000192837461928',
      swift: 'CIBEGXXX',
    },
  },
  {
    id: 'inv-2026-003',
    invoiceNumber: 'INV-2026-003',
    projectId: 'p4-apex-advisory',
    clientId: 'c1-apex-systems',
    issueDate: '2026-09-01',
    dueDate: '2026-09-16', // Past due!
    currency: 'USD',
    exchangeRateToLocal: 49.25,
    status: 'Overdue',
    items: [
      {
        id: 'item-3',
        description: 'September 2026 Cloud Architecture Retainer (25h allocation)',
        quantity: 1,
        unitPrice: 4500,
        amount: 4500,
      },
    ],
    subtotal: 4500,
    taxRate: 0,
    total: 4500,
    notes: 'Net 15 terms. Wire transfer details provided below.',
    paymentDetails: {
      bankName: 'Commercial International Bank (CIB)',
      accountHolder: 'Ibrahim Tarek',
      iban: 'EG380010004500000192837461928',
      swift: 'CIBEGXXX',
    },
  },
  {
    id: 'inv-2026-004',
    invoiceNumber: 'INV-2026-004',
    projectId: 'p3-nilepay-gateway',
    clientId: 'c3-nilepay',
    issueDate: '2026-09-18',
    dueDate: '2026-10-03',
    currency: 'EGP',
    exchangeRateToLocal: 1.0,
    status: 'Sent',
    items: [
      {
        id: 'item-4',
        description: 'Milestone 1: Security Compliance Audit & HSM Interface',
        quantity: 1,
        unitPrice: 70000,
        amount: 70000,
      },
    ],
    subtotal: 70000,
    taxRate: 0.14,
    total: 79800,
    notes: 'Includes 14% Egyptian VAT as per Egyptian Tax Authority regulations.',
    paymentDetails: {
      bankName: 'Commercial International Bank (CIB)',
      accountHolder: 'Tarek El-Masry',
      iban: 'EG380010004500000192837461928',
      swift: 'CIBEGXXX',
    },
  },
];

export const INITIAL_LEDGER: CashFlowLedgerEntry[] = [
  {
    id: 'tx-1',
    date: '2026-09-02',
    type: 'Inflow',
    category: 'Client Payment',
    originalAmount: 3500,
    currency: 'USD',
    exchangeRate: 49.25,
    baseAmount: 172375,
    notes: 'Payment for INV-2026-001 (Apex Cloud Milestone 1)',
    referenceId: 'inv-2026-001',
  },
  {
    id: 'tx-2',
    date: '2026-09-03',
    type: 'Outflow',
    category: 'Hosting',
    originalAmount: 145,
    currency: 'USD',
    exchangeRate: 49.25,
    baseAmount: 7141.25,
    notes: 'AWS Cloud production clusters & RDS staging instance',
  },
  {
    id: 'tx-3',
    date: '2026-09-05',
    type: 'Outflow',
    category: 'Subscription',
    originalAmount: 20,
    currency: 'USD',
    exchangeRate: 49.25,
    baseAmount: 985,
    notes: 'GitHub Copilot Business & Enterprise seat',
  },
  {
    id: 'tx-4',
    date: '2026-09-08',
    type: 'Outflow',
    category: 'Subscription',
    originalAmount: 39,
    currency: 'EUR',
    exchangeRate: 53.60,
    baseAmount: 2090.40,
    notes: 'JetBrains All Products Pack subscription (Monthly)',
  },
  {
    id: 'tx-5',
    date: '2026-09-12',
    type: 'Outflow',
    category: 'Hardware',
    originalAmount: 8500,
    currency: 'EGP',
    exchangeRate: 1.0,
    baseAmount: 8500,
    notes: 'Ergonomic mechanical split keyboard & backup NVMe drive',
  },
  {
    id: 'tx-6',
    date: '2026-09-15',
    type: 'Outflow',
    category: 'Overhead',
    originalAmount: 3200,
    currency: 'EGP',
    exchangeRate: 1.0,
    baseAmount: 3200,
    notes: 'Co-working space dedicated desk & fiber optic internet line',
  },
  {
    id: 'tx-7',
    date: '2026-08-15',
    type: 'Inflow',
    category: 'Client Payment',
    originalAmount: 4200,
    currency: 'USD',
    exchangeRate: 49.00,
    baseAmount: 205800,
    notes: 'Previous contract final milestone delivery',
  },
  {
    id: 'tx-8',
    date: '2026-08-18',
    type: 'Outflow',
    category: 'Hosting',
    originalAmount: 130,
    currency: 'USD',
    exchangeRate: 49.00,
    baseAmount: 6370,
    notes: 'Vercel Pro & Cloudflare Workers Enterprise pipeline',
  },
];
